### ISSUE TITLE
error

### ISSUE THREAD

**Issue by abolfazlMKazemi** [Poryaei/TapSwap-Clicker#11]
hello
i get this error
Exception in callback Cron.set_result(<_GatheringFu...assignment")]>)
handle: <Handle Cron.set_result(<_GatheringFu...assignment")]>)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/aiocron/__init__.py", line 112, in set_result
    raise result
  File "/root/TapSwap-Clicker/clicker.py", line 578, in sendTaps
    if not fulltank:
UnboundLocalError: local variable 'fulltank' referenced before assignment

**Comment by mrdarkerr** [comment]
me too 
'player'
Exception in callback Cron.set_result(<_GatheringFu...assignment")]>)
handle: <Handle Cron.set_result(<_GatheringFu...assignment")]>)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/dist-packages/aiocron/__init__.py", line 112, in set_result
    raise result
  File "clicker.py", line 578, in sendTaps
    if not fulltank:
UnboundLocalError: local variable 'fulltank' referenced before assignment

**Comment by M-logique** [comment]
The network is very busy and the web page takes a long time to take you to the Tap page

Wait for a while and restart the script

**Comment by Poryaei** [comment]
Thanks to @M-logique 🙏

The issue is from the server side of TAPSWAP, sometimes it can't handle the requests!
