### ISSUE TITLE
access_token

### ISSUE THREAD

**Issue by Kingprogrammer07** [Poryaei/TapSwap-Clicker#2]
Traceback (most recent call last):
  File "c:\Users\Administrator\Downloads\TapSwap-Clicker-main new\TapSwap-Clicker-main\clicker.py", line 513, in <module>
    auth = authToken(url)
           ^^^^^^^^^^^^^^
  File "c:\Users\Administrator\Downloads\TapSwap-Clicker-main new\TapSwap-Clicker-main\clicker.py", line 116, in authToken
    return response['access_token']
           ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'

**Comment by THMaST3R** [comment]
same error

**Comment by Poryaei** [comment]
Fixed
