### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 5 column 21 (char 123)

### ISSUE THREAD

**Issue by EXE88** [Poryaei/TapSwap-Clicker#20]
why when i run clicker.py i got this error ??

Traceback (most recent call last):
  File "clicker.py", line 13, in <module>
    data = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 21 (char 123)

**Comment by Poryaei** [comment]
Are you using the latest version?

**Comment by EXE88** [comment]
Yeah i just installed minutes ago from this github repository

**Comment by Poryaei** [comment]
Ok pls update again and try

**Comment by Poryaei** [comment]
Use the latest version of the robot.
