### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by Aka-Bobur** [Poryaei/TapSwap-Clicker#21]
'player'
Exception in callback Cron.set_result(<_GatheringFu...assignment")]>)
handle: <Handle Cron.set_result(<_GatheringFu...assignment")]>)>
Traceback (most recent call last):
  File "C:\Program Files\Python3913\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\TSNQB\Desktop\TapSwap-Clicker\.venv\lib\site-packages\aiocron\__init__.py", line 112, in set_result
    raise result
  File "c:\Users\TSNQB\Desktop\TapSwap-Clicker\clicker.py", line 610, in sendTaps
    time_to_recharge = ((energy_level*500)-energy) / charge_level
UnboundLocalError: local variable 'energy_level' referenced before assignment

**Comment by Aka-Bobur** [comment]
"auto_upgrade": false,
    "max_charge_level": 5,
    "max_energy_level": 16,
    "max_tap_level": 16
}

**Comment by Poryaei** [comment]
Use the latest version of the robot.
