### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ppouria** [Poryaei/TapSwap-Clicker#23]
Client is Ready ;)
Traceback (most recent call last):
  File "/root/tap/TapSwap-Clicker/clicker.py", line 37, in <module>
    client.send_message('tapswap_bot', f'/start r_{admin}')
  File "/usr/local/lib/python3.10/dist-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/messages.py", line 905, in send_message
    result = await self(request)
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.UserIsBotError: Bots can't send messages to other bots (caused by SendMessageRequest)
Segmentation fault (core dumped)

**Comment by Poryaei** [comment]
Run clicker on your phone number
